package za.ac.cput.Service.impl;

import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;
import za.ac.cput.domain.JobSeeker;
import za.ac.cput.factory.JobSeekerFactory;
import za.ac.cput.repository.IJobSeekerRepository;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
@Transactional
class JobSeekerServiceImplTest {

    @Autowired
    private JobSeekerServiceImpl jobSeekerService;

    @Autowired
    private IJobSeekerRepository jobSeekerRepository;


    @BeforeEach
    void setUp() {
        jobSeekerRepository.deleteAll();
    }


    @Test
    @Order(1)
    void create() {

        JobSeeker jobSeeker = createTestJobSeeker();

        assertNotNull(jobSeeker);

        JobSeeker created = jobSeekerService.create(jobSeeker);

        assertNotNull(created);
        assertNotNull(created.getUserId());

        System.out.println("Created JobSeeker: "
                + created.getFirstName()
                + " "
                + created.getLastName());

        System.out.println("ID: " + created.getUserId());
    }


    @Test
    @Order(2)
    void read() {

        JobSeeker saved = jobSeekerService.create(createTestJobSeeker());

        JobSeeker found = jobSeekerService.read(saved.getUserId());

        assertNotNull(found);
        assertEquals(saved.getUserId(), found.getUserId());

        System.out.println("Read JobSeeker: "
                + found.getFirstName());
    }


    @Test
    @Order(3)
    void update() {

        JobSeeker saved = jobSeekerService.create(createTestJobSeeker());


        JobSeeker updatedJobSeeker = new JobSeeker.Builder()
                .copy(saved)
                .setFirstName("Name Updated")
                .setLastName("Surname Updated")
                .setProfilePicture("updated_profile.png")
                .setPhoneNumber("0823456789")
                .setLocation("Johannesburg")
                .setHeadline("Senior Java Software Engineer")
                .setSummary("Updated summary")
                .setResumePath("updated_resume.pdf")
                .build();


        JobSeeker updated = jobSeekerService.update(updatedJobSeeker);

        assertNotNull(updated);
        assertEquals(saved.getUserId(), updated.getUserId());

        System.out.println("Updated JobSeeker: "
                + updated.getFirstName());
    }


    @Test
    @Order(4)
    void delete() {

        JobSeeker saved = jobSeekerService.create(createTestJobSeeker());

        String id = saved.getUserId();

        boolean deleted = jobSeekerService.delete(id);

        assertTrue(deleted);

        JobSeeker found = jobSeekerService.read(id);

        assertNull(found);

        System.out.println("Deleted JobSeeker: " + id);
    }


    @Test
    @Order(5)
    void getAll() {

        jobSeekerService.create(createTestJobSeeker());
        jobSeekerService.create(createTestJobSeeker());


        List<JobSeeker> jobSeekers = jobSeekerService.getAll();


        assertNotNull(jobSeekers);
        assertEquals(2, jobSeekers.size());


        System.out.println("Found "
                + jobSeekers.size()
                + " JobSeekers");
    }


    @Test
    @Order(6)
    void getByEmail() {

        JobSeeker saved = jobSeekerService.create(createTestJobSeeker());


        List<JobSeeker> found =
                jobSeekerService.getByEmail(saved.getEmail());


        assertNotNull(found);
        assertFalse(found.isEmpty());


        System.out.println(
                "Found JobSeeker with email: "
                        + saved.getEmail()
        );
    }


    @Test
    @Order(7)
    void getByEmailNotFound() {

        List<JobSeeker> found =
                jobSeekerService.getByEmail("doesnotexist@gmail.com");


        assertNotNull(found);
        assertTrue(found.isEmpty());
    }


    @Test
    @Order(8)
    void createJobSeekerWithAutoGeneratedId() {


        JobSeeker jobSeeker =
                JobSeekerFactory.createJobSeeker(
                        "auto@gmail.com",
                        "password123",
                        "Auto",
                        "Generated",
                        "profile.png",
                        "0711111111",
                        "Cape Town",
                        "Software Developer",
                        "Testing UUID generation",
                        "resume.pdf",
                        "Java",
                        "BSc Computer Science"
                );


        assertNotNull(jobSeeker);
        assertNotNull(jobSeeker.getUserId());


        JobSeeker created =
                jobSeekerService.create(jobSeeker);


        assertNotNull(created);
        assertNotNull(created.getUserId());


        System.out.println(
                "Created JobSeeker ID: "
                        + created.getUserId()
        );
    }


    private JobSeeker createTestJobSeeker() {

        return JobSeekerFactory.createJobSeeker(
                "test" + System.currentTimeMillis() + "@gmail.com",
                "securePassword123",
                "Test",
                "User",
                "profile_picture.png",
                "0712345678",
                "Cape Town",
                "Software Engineer",
                "Test summary for job seeker",
                "test_resume.pdf",
                "Java, Spring Boot",
                "BSc Computer Science"
        );
    }
}
