package za.ac.cput.factory;

import za.ac.cput.domain.Employer;
import za.ac.cput.util.Helper;

import java.util.ArrayList;

public class EmployerFactory {

    /**
     * Create an Employer with required fields
     * userId will be auto-generated by JPA
     */
    public static Employer createEmployer(String email, String password,
                                          String firstName, String lastName,
                                          String companyName, String industry) {
        if (Helper.isNullOrEmpty(email) ||
                !Helper.isValidEmail(email) ||
                Helper.isNullOrEmpty(password) ||
                Helper.isNullOrEmpty(companyName) ||
                Helper.isNullOrEmpty(industry)) {
            return null;
        }

        return Employer.builder()
                .email(email)
                .password(password)
                .firstName(firstName)
                .lastName(lastName)
                .companyName(companyName)
                .industry(industry)
                .postedJobs(new ArrayList<>())
                .build();
    }

    /**
     * Create a complete Employer with all fields
     * userId will be auto-generated by JPA
     */
    public static Employer createEmployer(String email, String password,
                                          String firstName, String lastName,
                                          String profilePicture, String phoneNumber,
                                          String location,
                                          String companyName, String companyWebsite,
                                          String companySize, String industry,
                                          String companyLogo, String companyDescription,
                                          String companyHeadquarters) {
        if (Helper.isNullOrEmpty(email) ||
                !Helper.isValidEmail(email) ||
                Helper.isNullOrEmpty(password) ||
                Helper.isNullOrEmpty(firstName) ||
                Helper.isNullOrEmpty(lastName) ||
                Helper.isNullOrEmpty(companyName) ||
                Helper.isNullOrEmpty(industry)) {
            return null;
        }

        return Employer.builder()
                .email(email)
                .password(password)
                .firstName(firstName)
                .lastName(lastName)
                .profilePicture(profilePicture)
                .phoneNumber(phoneNumber)
                .location(location)
                .companyName(companyName)
                .companyWebsite(companyWebsite)
                .companySize(companySize)
                .industry(industry)
                .companyLogo(companyLogo)
                .companyDescription(companyDescription)
                .companyHeadquarters(companyHeadquarters)
                .postedJobs(new ArrayList<>())
                .build();
    }
}