package za.ac.cput.factory;

import za.ac.cput.domain.JobSeeker;
import za.ac.cput.util.Helper;

import java.util.ArrayList;

public class JobSeekerFactory {

    /**
     * Create a JobSeeker with required fields
     * userId will be auto-generated by JPA
     */
    public static JobSeeker createJobSeeker(String email, String password,
                                            String firstName, String lastName,
                                            String headline, String summary) {
        if (Helper.isNullOrEmpty(email) ||
                !Helper.isValidEmail(email) ||
                Helper.isNullOrEmpty(password) ||
                Helper.isNullOrEmpty(firstName) ||
                Helper.isNullOrEmpty(lastName) ||
                Helper.isNullOrEmpty(headline) ||
                Helper.isNullOrEmpty(summary)) {
            return null;
        }

        return JobSeeker.builder()
                .email(email)
                .password(password)
                .firstName(firstName)
                .lastName(lastName)
                .headline(headline)
                .summary(summary)
                .skills(new ArrayList<>())
                .experiences(new ArrayList<>())
                .educations(new ArrayList<>())
                .build();
    }

    /**
     * Create a complete JobSeeker with all fields
     * userId will be auto-generated by JPA
     */
    public static JobSeeker createJobSeeker(String email, String password,
                                            String firstName, String lastName,
                                            String profilePicture, String phoneNumber,
                                            String location,
                                            String headline, String summary,
                                            String resumePath) {
        if (Helper.isNullOrEmpty(email) ||
                !Helper.isValidEmail(email) ||
                Helper.isNullOrEmpty(password) ||
                Helper.isNullOrEmpty(firstName) ||
                Helper.isNullOrEmpty(lastName) ||
                Helper.isNullOrEmpty(headline) ||
                Helper.isNullOrEmpty(summary)) {
            return null;
        }

        return JobSeeker.builder()
                .email(email)
                .password(password)
                .firstName(firstName)
                .lastName(lastName)
                .profilePicture(profilePicture)
                .phoneNumber(phoneNumber)
                .location(location)
                .headline(headline)
                .summary(summary)
                .resumePath(resumePath)
                .skills(new ArrayList<>())
                .experiences(new ArrayList<>())
                .educations(new ArrayList<>())
                .build();
    }
}